Repository 4ilet/Find_Toilet, pull requests merged in 2023-05, with the labels that each got.

#109 #38 [BE-장엽] chore : 리뷰 여부 확인 코드 추가
  backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ReviewRepository.java
  backend/src/main/java/com/Fourilet/project/fourilet/dto/ToiletDto.java
  backend/src/main/java/com/Fourilet/project/fourilet/dto/ToiletDto2.java
  backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java
Labels: BE

#110 #38 [BE-윤주] chore: 화장실 API 리뷰 작성 여부 확인 추가
  backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ToiletRepositoryImpl.java
  backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java
  backend/src/main/java/com/Fourilet/project/fourilet/service/ToiletService.java
Labels: BE

#111 #38 [BE-장엽] chore : 리뷰목록 조회 상태코드 변경
  backend/src/main/java/com/Fourilet/project/fourilet/controller/ReviewController.java
  backend/src/main/java/com/Fourilet/project/fourilet/dto/StatusEnum.java
Labels: BE

#113 #38 [BE-장엽] feat: 개별리뷰조회 api추가
  backend/src/main/java/com/Fourilet/project/fourilet/controller/ReviewController.java
  backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ReviewRepository.java
  backend/src/main/java/com/Fourilet/project/fourilet/service/ReviewService.java
Labels: BE

#115 #104 [BE-윤주] docs: Readme 기술 스택 수정, 시스템 아키텍처 추가
  README.md
  assets/system_architecture.jpeg
Labels: documentation

#117 [FE] feat: 화장실 목록 및 리뷰 조회, 외부 내비게이션 앱 연결, 리뷰 수정, 리뷰 및 즐겨찾기 삭제
  frontend/.gitignore
  frontend/lib/main.dart
  frontend/lib/models/review_model.dart
  frontend/lib/models/toilet_model.dart
  frontend/lib/providers/api_provider.dart
  frontend/lib/providers/bookmark_provider.dart
  frontend/lib/providers/review_provider.dart
  frontend/lib/providers/state_provider.dart
  frontend/lib/providers/toilet_provider.dart
  frontend/lib/providers/user_provider.dart
  frontend/lib/screens/book_mark_screen.dart
  frontend/lib/screens/intro_screen.dart
  frontend/lib/screens/main_screen.dart
  frontend/lib/screens/review_form_screen.dart
  frontend/lib/screens/search_screen.dart
  frontend/lib/screens/select_theme_screen.dart
  frontend/lib/screens/settings_screen.dart
  frontend/lib/utilities/global_utils.dart
  frontend/lib/utilities/settings_utils.dart
  frontend/lib/widgets/bottom_sheet.dart
  frontend/lib/widgets/box_container.dart
  frontend/lib/widgets/list_view.dart
  frontend/lib/widgets/modal.dart
  frontend/lib/widgets/scroll_view.dart
  frontend/lib/widgets/search_bar.dart
  frontend/lib/widgets/silvers.dart
  frontend/pubspec.lock
Labels: FE

#120 #38 [BE-윤주] chore : 화장실 API null 오류 수정
  README.md
Labels: BE

#121 #38 [BE-윤주] chore: 데이터 최대 개수 150개로 제한
  backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ToiletRepositoryImpl.java
Labels: BE

#122 #104 [BE-윤주] docs: README 개발 기간 수정
  README.md
Labels: BE

#123 #104 [BE-윤주] docs: README 개발 기간 수정
  README.md
  backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ToiletRepositoryImpl.java
Labels: documentation

#124 [BE-장엽] chore: review 최신순 정렬
  backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ReviewRepository.java
  backend/src/main/java/com/Fourilet/project/fourilet/service/ReviewService.java
Labels: BE

#126 [BE-장엽] chore: review 최신순 정렬
  backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ReviewRepository.java
  backend/src/main/java/com/Fourilet/project/fourilet/service/ReviewService.java
Labels: BE

#127 [BE-장엽] chore : 전체리뷰 사이즈 반환 수정
  backend/src/main/java/com/Fourilet/project/fourilet/controller/ReviewController.java
  backend/src/main/java/com/Fourilet/project/fourilet/dto/ReviewDto.java
  backend/src/main/java/com/Fourilet/project/fourilet/service/ReviewService.java
Labels: BE

#128 [BE-장엽] chore : 전체 페이지 수 반환 수정
  backend/src/main/java/com/Fourilet/project/fourilet/dto/ReviewDto.java
  backend/src/main/java/com/Fourilet/project/fourilet/service/ReviewService.java
Labels: BE

#131 #38 [BE-윤주] chore: 북마크 여부 폴더 id 리스트로 변경
  backend/src/main/java/com/Fourilet/project/fourilet/controller/FolderController.java
  backend/src/main/java/com/Fourilet/project/fourilet/data/repository/BookMarkRepository.java
  backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ToiletRepositoryImpl.java
  backend/src/main/java/com/Fourilet/project/fourilet/dto/ToiletDto.java
  backend/src/main/java/com/Fourilet/project/fourilet/dto/ToiletDto2.java
  backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java
  backend/src/main/java/com/Fourilet/project/fourilet/service/ToiletService.java
Labels: BE

#132 [BE-장엽] chore : 즐겨찾기 폴더 삭제 제한 추가, 폴더 내의 화장실 목록에 페이지네이션 적용
  backend/src/main/java/com/Fourilet/project/fourilet/controller/FolderController.java
  backend/src/main/java/com/Fourilet/project/fourilet/controller/ReviewController.java
  backend/src/main/java/com/Fourilet/project/fourilet/data/repository/BookMarkRepository.java
  backend/src/main/java/com/Fourilet/project/fourilet/dto/Message.java
  backend/src/main/java/com/Fourilet/project/fourilet/dto/ToiletDto2.java
  backend/src/main/java/com/Fourilet/project/fourilet/exception/AtLeastException.java
  backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java
Labels: BE

#135 [FE] feat: 스크롤 기능, 검색 화면 수정, 설정 화면 수정
  frontend/lib/main.dart
  frontend/lib/models/toilet_model.dart
  frontend/lib/providers/api_provider.dart
  frontend/lib/providers/bookmark_provider.dart
  frontend/lib/providers/review_provider.dart
  frontend/lib/providers/state_provider.dart
  frontend/lib/providers/toilet_provider.dart
  frontend/lib/providers/user_provider.dart
  frontend/lib/screens/book_mark_folder_screen.dart
  frontend/lib/screens/book_mark_screen.dart
  frontend/lib/screens/intro_screen.dart
  frontend/lib/screens/main_screen.dart
  frontend/lib/screens/search_screen.dart
  frontend/lib/screens/select_theme_screen.dart
  frontend/lib/screens/settings_screen.dart
  frontend/lib/utilities/global_utils.dart
  frontend/lib/utilities/icon_image.dart
  frontend/lib/utilities/settings_utils.dart
  frontend/lib/widgets/bottom_sheet.dart
  frontend/lib/widgets/box_container.dart
  frontend/lib/widgets/modal.dart
  frontend/lib/widgets/scroll_view.dart
  frontend/lib/widgets/search_bar.dart
  frontend/lib/widgets/silvers.dart
  frontend/lib/widgets/text_widget.dart
Labels: FE

#137 #38 [BE-윤주] chore : API Token FE 테스트를 위해 유효기간 변경
  backend/src/main/resources/application.yml
Labels: BE

#138 [BE-장엽] chore : 토큰테스트를 위한 유효기간 변경
  backend/src/main/resources/application.yml
Labels: BE

#139 [BE-장엽] chore : 토큰테스트를 위한 유효기간 변경
  backend/src/main/resources/application.yml
Labels: BE

#141 #38 [BE-윤주] chore: token 만료 시 응답값 변경 테스트
  backend/src/main/java/com/Fourilet/project/fourilet/config/SwaggerConfig.java
  backend/src/main/java/com/Fourilet/project/fourilet/config/jwt/filter/JwtAuthenticationProcessingFilter.java
  backend/src/main/java/com/Fourilet/project/fourilet/controller/ToiletController.java
  backend/src/main/resources/application.yml
Labels: BE

#142 #38 [BE-윤주] chore: 토큰 만료 시 access와 refresh 구분 테스트
  backend/src/main/java/com/Fourilet/project/fourilet/config/jwt/filter/JwtAuthenticationProcessingFilter.java
  backend/src/main/resources/application.yml
Labels: BE

#143 #38 [BE-윤주] chore: 리프레시&액세스 토큰 만료 및 유효성 구분
  backend/src/main/java/com/Fourilet/project/fourilet/config/jwt/filter/JwtAuthenticationProcessingFilter.java
  backend/src/main/resources/application.yml
Labels: BE

#144 #38 [BE-윤주] chore: 액세스 토큰이 유효하지 않은 경우 상태 코드 변경
  backend/src/main/java/com/Fourilet/project/fourilet/config/jwt/filter/JwtAuthenticationProcessingFilter.java
Labels: BE

#145 #38 [BE-윤주] chore: 화장실 리뷰 조회 토큰 검사 로직 수정
  backend/src/main/java/com/Fourilet/project/fourilet/config/jwt/filter/JwtAuthenticationProcessingFilter.java
Labels: BE

#146 [BE-장엽] chore : 다중 폴더에 화장실 추가 삭제로 수정
  backend/src/main/java/com/Fourilet/project/fourilet/controller/FolderController.java
  backend/src/main/java/com/Fourilet/project/fourilet/dto/FolderDto.java
  backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java
  backend/src/main/resources/application.yml
Labels: BE

#147 [FE] feat : 무한 스크롤 적용 및 토큰 리프레시 기능 추가, 리뷰 CRUD 점검, 닉네임 변경 오류 수정
  frontend/lib/providers/api_provider.dart
  frontend/lib/providers/bookmark_provider.dart
  frontend/lib/providers/review_provider.dart
  frontend/lib/providers/state_provider.dart
  frontend/lib/providers/toilet_provider.dart
  frontend/lib/providers/user_provider.dart
  frontend/lib/screens/book_mark_folder_screen.dart
  frontend/lib/screens/book_mark_screen.dart
  frontend/lib/screens/intro_screen.dart
  frontend/lib/screens/main_screen.dart
  frontend/lib/screens/review_form_screen.dart
  frontend/lib/screens/search_screen.dart
  frontend/lib/screens/settings_screen.dart
  frontend/lib/utilities/global_utils.dart
  frontend/lib/widgets/bottom_sheet.dart
  frontend/lib/widgets/box_container.dart
  frontend/lib/widgets/modal.dart
  frontend/lib/widgets/scroll_view.dart
  frontend/lib/widgets/search_bar.dart
  frontend/lib/widgets/silvers.dart
  frontend/lib/widgets/text_widget.dart
Labels: FE
