Repository 4ilet/Find_Toilet, pull requests merged in 2023-04, with the labels that each got.

#90 [FE] feat: 로그인 기능 구현 완료
  frontend/.gitignore
  frontend/android/app/build.gradle
  frontend/android/app/src/main/AndroidManifest.xml
  frontend/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  frontend/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  frontend/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  frontend/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  frontend/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  frontend/lib/main.dart
  frontend/lib/models/bookmark_model.dart
  frontend/lib/models/review_model.dart
  frontend/lib/models/toilet_model.dart
  frontend/lib/providers/api_provider.dart
  frontend/lib/providers/bookmark_provider.dart
  frontend/lib/providers/review_provider.dart
  frontend/lib/providers/state_provider.dart
  frontend/lib/providers/user_provider.dart
  frontend/lib/screens/book_mark_screen.dart
  frontend/lib/screens/intro_screen.dart
  frontend/lib/screens/main_screen.dart
  frontend/lib/screens/review_form_screen.dart
  frontend/lib/screens/select_theme_screen.dart
  frontend/lib/screens/settings_screen.dart
  frontend/lib/utilities/global_utils.dart
  frontend/lib/utilities/settings_utils.dart
  frontend/lib/utilities/style.dart
  frontend/lib/utilities/type_enum.dart
  frontend/lib/widgets/bottom_sheet.dart
  frontend/lib/widgets/box_container.dart
  frontend/lib/widgets/button.dart
  frontend/lib/widgets/modal.dart
  frontend/lib/widgets/search_bar.dart
  frontend/lib/widgets/select_box.dart
  frontend/lib/widgets/text_widget.dart
  frontend/linux/flutter/generated_plugin_registrant.cc
  frontend/linux/flutter/generated_plugins.cmake
  frontend/macos/Flutter/GeneratedPluginRegistrant.swift
  frontend/pubspec.lock
  frontend/pubspec.yaml
  frontend/windows/flutter/generated_plugin_registrant.cc
  frontend/windows/flutter/generated_plugins.cmake
Labels: FE

#92 #38 [BE-윤주] chore : Member API 요구사항 반영
  backend/src/main/java/com/Fourilet/project/fourilet/config/jwt/filter/JwtAuthenticationProcessingFilter.java
  backend/src/main/java/com/Fourilet/project/fourilet/controller/MemberController.java
  backend/src/main/java/com/Fourilet/project/fourilet/data/entity/Member.java
  backend/src/main/java/com/Fourilet/project/fourilet/data/repository/MemberRepository.java
  backend/src/main/java/com/Fourilet/project/fourilet/service/MemberService.java
Labels: BE

#93 [BE-장엽] feat : accessToken으로 member 식별 코드 작성
  backend/src/main/java/com/Fourilet/project/fourilet/controller/FolderController.java
  backend/src/main/java/com/Fourilet/project/fourilet/controller/ReviewController.java
  backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ReviewRepository.java
  backend/src/main/java/com/Fourilet/project/fourilet/dto/PageDto.java
Labels: bug, BE

#94 [BE-장엽] feat : review 목록 페이지네이션 적용
  backend/src/main/java/com/Fourilet/project/fourilet/controller/ReviewController.java
  backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ReviewRepository.java
  backend/src/main/java/com/Fourilet/project/fourilet/dto/PageDto.java
  backend/src/main/java/com/Fourilet/project/fourilet/service/ReviewService.java
Labels: BE

#96 [BE-장엽] feat: 즐겨찾기 명 10자이내로 제한
  backend/src/main/java/com/Fourilet/project/fourilet/controller/FolderController.java
  backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java
Labels: BE

#97 #38 [BE-윤주] chore: 닉네임 수정 10자 제한
  backend/src/main/java/com/Fourilet/project/fourilet/controller/MemberController.java
  backend/src/main/java/com/Fourilet/project/fourilet/service/MemberService.java
Labels: BE

#100 [FE] feat: 로그인 데이터 상태 관리 및 자동 로그인, 화면 새로고침
  frontend/.gitignore
  frontend/lib/main.dart
  frontend/lib/providers/api_provider.dart
  frontend/lib/providers/bookmark_provider.dart
  frontend/lib/providers/review_provider.dart
  frontend/lib/providers/state_provider.dart
  frontend/lib/providers/user_provider.dart
  frontend/lib/screens/book_mark_screen.dart
  frontend/lib/screens/intro_screen.dart
  frontend/lib/screens/review_form_screen.dart
  frontend/lib/screens/select_theme_screen.dart
  frontend/lib/screens/settings_screen.dart
  frontend/lib/utilities/global_utils.dart
  frontend/lib/utilities/icon_image.dart
  frontend/lib/utilities/settings_utils.dart
  frontend/lib/utilities/type_enum.dart
  frontend/lib/widgets/bottom_sheet.dart
  frontend/lib/widgets/box_container.dart
  frontend/lib/widgets/modal.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: FE

#105 #38 [BE-윤주] chore: 즐겨찾기 & 화장실 dto 동일하도록 수정
  README.md
  assets/erd.jpeg
  assets/figma.png
  backend/build.gradle
  backend/src/main/java/com/Fourilet/project/fourilet/dto/ToiletDto2.java
  backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java
Labels: BE

#106 #38 [BE-윤주] chore: security review 조회 권한 수정
  backend/src/main/java/com/Fourilet/project/fourilet/config/SecurityConfig.java
Labels: BE

#107 #38 [BE-윤주] chore: 화장실 API 북마크 여부 데이터 반환 수정
  backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ToiletRepository.java
  backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ToiletRepositoryImpl.java
  backend/src/main/java/com/Fourilet/project/fourilet/dto/ToiletDto.java
  backend/src/main/java/com/Fourilet/project/fourilet/service/ToiletService.java
Labels: BE

#108 #38 [BE-윤주] chore: 즐겨찾기 폴더 내 화장실 목록의 북마크 여부를 forderId로 수정
  backend/src/main/java/com/Fourilet/project/fourilet/controller/FolderController.java
  backend/src/main/java/com/Fourilet/project/fourilet/dto/ToiletDto2.java
  backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java
Labels: BE
